# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.TextField(default='1.jpg'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ingress',
            field=models.TextField(max_length=100),
        ),
    ]
