# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 20:21
from __future__ import unicode_literals

import apps.articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20161230_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=apps.articles.models.image_path),
        ),
    ]
